apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  labels:
    app: jenkins
spec:
  storageClassName: default-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi