version: "3.8"

services:
  auth:
    image: "coolexplorer/spring-micro-auth:0.1.14-dev"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SERVER_PORT: 8080
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_ADDRESSES: "localhost:29092"
      LOGGING_LEVEL_IO_COOLEXPLORER: DEBUG
    volumes:
      - $PWD/logs/auth:/logs
    networks: 
      - spring-micro

  session:
    image: "coolexplorer/spring-micro-session:0.1.5-dev"
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      SERVER_PORT: 8080
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_ADDRESSES: "localhost:29092"
      LOGGING_LEVEL_IO_COOLEXPLORER: DEBUG
    networks: 
      - spring-micro

networks:
  spring-micro:
    driver: bridge