apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.global.appName }}-pv"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
spec:
  capacity:
    storage: {{ .Values.global.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default-local-storage
  local:
    path: /Users/kimseunghwan/pv/redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
